"""Add gates and gate_bookings for truck appointment system

Revision ID: 113ddf41ede3
Revises: 17aa82831d8c
Create Date: 2026-09-15 14:38:31.354463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113ddf41ede3'
down_revision = '17aa82831d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gate_type', sa.Enum('Container Terminal', 'Bulk Cargo', 'General / Mixed', 'Tanker / Liquid Cargo', name='gatetype'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Closed', 'Maintenance', name='gatestatus'), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('capacity_per_hour', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gates_gate_code'), ['gate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gates_gate_type'), ['gate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gates_status'), ['status'], unique=False)

    op.create_table('gate_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('booked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('truck_number', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Enum('Container Pickup', 'Container Delivery', 'Cargo Pickup', 'Cargo Delivery', 'Empty Return', 'Other', name='bookingpurpose'), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('slot_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Booked', 'Checked In', 'Completed', 'Cancelled', 'No Show', name='bookingstatus'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gate_bookings', schema=None) as batch_op:
        batch_op.create_index('ix_gate_booking_slot', ['gate_id', 'slot_start'], unique=False)
        batch_op.create_index('ix_gate_booking_status_slot', ['status', 'slot_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_booked_by_user_id'), ['booked_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_container_id'), ['container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_gate_id'), ['gate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_slot_start'), ['slot_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_bookings_truck_id'), ['truck_id'], unique=False)

    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_gate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trucks_current_gate_id'), ['current_gate_id'], unique=False)
        batch_op.create_foreign_key(None, 'gates', ['current_gate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trucks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trucks_current_gate_id'))
        batch_op.drop_column('current_gate_id')

    with op.batch_alter_table('gate_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gate_bookings_truck_id'))
        batch_op.drop_index(batch_op.f('ix_gate_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_gate_bookings_slot_start'))
        batch_op.drop_index(batch_op.f('ix_gate_bookings_gate_id'))
        batch_op.drop_index(batch_op.f('ix_gate_bookings_container_id'))
        batch_op.drop_index(batch_op.f('ix_gate_bookings_booked_by_user_id'))
        batch_op.drop_index('ix_gate_booking_status_slot')
        batch_op.drop_index('ix_gate_booking_slot')

    op.drop_table('gate_bookings')
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gates_status'))
        batch_op.drop_index(batch_op.f('ix_gates_gate_type'))
        batch_op.drop_index(batch_op.f('ix_gates_gate_code'))

    op.drop_table('gates')
    # ### end Alembic commands ###
