"""Add jti/refresh_jti to sessions for real token revocation

Revision ID: 17aa82831d8c
Revises: a705a0efec77
Create Date: 2026-09-14 11:23:23.200932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aa82831d8c'
down_revision = 'a705a0efec77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('refresh_jti', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_refresh_jti'), ['refresh_jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_jti'))
        batch_op.drop_index(batch_op.f('ix_sessions_jti'))
        batch_op.drop_column('refresh_jti')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
